# Originally derived from AiogramBotTemplate (https://github.com/arturboyun/AiogramBotTemplate)
# Copyright (c) 2024 Artur Boyun. MIT License. See THIRD_PARTY_NOTICES.md.
#
# 0001_initial — the whole M1 schema in one migration: extensions, the two transaction enums,
# all 11 tables (FK-dependency order), and their indexes. Autogenerated from the models, then
# hand-edited to add the CREATE EXTENSION / CREATE TYPE statements autogenerate cannot emit.

"""initial

Revision ID: 0001_initial
Revises:
Create Date: 2026-07-11 18:31:32.168996

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0001_initial"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Extensions: ltree (categories.parents_tree), pgcrypto (gen_random_uuid), btree_gist
    # (required for the composite GIST index on categories(book_id, parents_tree) — a bigint
    # column has no default gist opclass without it).
    op.execute("CREATE EXTENSION IF NOT EXISTS ltree")
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")

    # Native enum types (create_type=False on the columns below, so they are managed here).
    op.execute(
        "CREATE TYPE transaction_kind AS ENUM ('plain_cash', 'internal_transfer', 'fx_conversion')"
    )
    op.execute("CREATE TYPE transaction_direction AS ENUM ('buy', 'sell')")

    op.create_table(
        "exchange_rates",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("base_currency_code", sa.String(length=8), nullable=False),
        sa.Column("quote_currency_code", sa.String(length=8), nullable=False),
        sa.Column("rate", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_exchange_rates")),
        sa.UniqueConstraint(
            "base_currency_code",
            "quote_currency_code",
            "source",
            "fetched_at",
            name="uq_exchange_rates_base_quote_source_fetched",
        ),
    )
    op.create_index(
        "ix_exchange_rates_base_quote_fetched",
        "exchange_rates",
        ["base_currency_code", "quote_currency_code", sa.literal_column("fetched_at DESC")],
        unique=False,
    )
    op.create_table(
        "users",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("telegram_user_id", sa.BigInteger(), nullable=False),
        sa.Column("telegram_username", sa.Text(), nullable=True),
        sa.Column("first_name", sa.Text(), nullable=True),
        sa.Column("last_name", sa.Text(), nullable=True),
        sa.Column("language", sa.Text(), server_default="en", nullable=False),
        sa.Column("timezone", sa.Text(), server_default="UTC", nullable=False),
        sa.Column("is_blocked", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("telegram_user_id", name=op.f("uq_users_telegram_user_id")),
    )
    op.create_table(
        "books",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("owner_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("kind", sa.SmallInteger(), nullable=False),
        sa.Column("base_currency_code", sa.String(length=8), nullable=False),
        sa.Column("default_language", sa.Text(), server_default="en", nullable=False),
        sa.Column("archived", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], name=op.f("fk_books_owner_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_books")),
    )
    op.create_table(
        "accounts",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("book_id", sa.BigInteger(), nullable=False),
        sa.Column("currency_code", sa.String(length=8), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("kind", sa.SmallInteger(), nullable=False),
        sa.Column("archived", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "opening_balance",
            sa.Numeric(precision=20, scale=8),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["book_id"], ["books.id"], name=op.f("fk_accounts_book_id_books")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_accounts")),
    )
    op.create_table(
        "book_invites",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("book_id", sa.BigInteger(), nullable=False),
        sa.Column("invited_by", sa.BigInteger(), nullable=False),
        sa.Column("token", sa.Text(), nullable=False),
        sa.Column("role", sa.SmallInteger(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["book_id"], ["books.id"], name=op.f("fk_book_invites_book_id_books")
        ),
        sa.ForeignKeyConstraint(
            ["invited_by"], ["users.id"], name=op.f("fk_book_invites_invited_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_book_invites")),
        sa.UniqueConstraint("token", name=op.f("uq_book_invites_token")),
    )
    op.create_table(
        "book_members",
        sa.Column("book_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("role", sa.SmallInteger(), nullable=False),
        sa.Column(
            "invited_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["book_id"], ["books.id"], name=op.f("fk_book_members_book_id_books")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_book_members_user_id_users")
        ),
        sa.PrimaryKeyConstraint("book_id", "user_id", name=op.f("pk_book_members")),
    )
    op.create_table(
        "categories",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("book_id", sa.BigInteger(), nullable=False),
        sa.Column("parents_tree", sqlalchemy_utils.types.ltree.LtreeType(), nullable=False),
        sa.Column("kind", sa.SmallInteger(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("archived", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["book_id"], ["books.id"], name=op.f("fk_categories_book_id_books")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_categories")),
    )
    op.create_index(
        "ix_categories_book_id_parents_tree",
        "categories",
        ["book_id", "parents_tree"],
        unique=False,
        postgresql_using="gist",
    )
    op.create_table(
        "currencies",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("book_id", sa.BigInteger(), nullable=True),
        sa.Column("code", sa.String(length=8), nullable=False),
        sa.Column("symbol", sa.Text(), nullable=False),
        sa.Column("decimals", sa.SmallInteger(), nullable=False),
        sa.Column("kind", sa.SmallInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("archived", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["book_id"], ["books.id"], name=op.f("fk_currencies_book_id_books")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_currencies")),
        sa.UniqueConstraint("book_id", "code", name="uq_currencies_book_id_code"),
    )
    op.create_table(
        "notifications_outbox",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("book_id", sa.BigInteger(), nullable=True),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempts", sa.SmallInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["book_id"], ["books.id"], name=op.f("fk_notifications_outbox_book_id_books")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_notifications_outbox_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications_outbox")),
    )
    op.create_index(
        "ix_notifications_outbox_undelivered",
        "notifications_outbox",
        ["created_at"],
        unique=False,
        postgresql_where=sa.text("delivered_at IS NULL"),
    )
    op.create_table(
        "tg_chats",
        sa.Column("chat_id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("active_book_id", sa.BigInteger(), nullable=True),
        sa.Column("last_message_id", sa.BigInteger(), nullable=True),
        sa.Column("ui_mode", sa.SmallInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("gpt_mode", sa.SmallInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("hide_amounts", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["active_book_id"], ["books.id"], name=op.f("fk_tg_chats_active_book_id_books")
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_tg_chats_user_id_users")),
        sa.PrimaryKeyConstraint("chat_id", name=op.f("pk_tg_chats")),
    )
    op.create_table(
        "fx_transactions",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("book_id", sa.BigInteger(), nullable=False),
        sa.Column("created_by_user_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "kind",
            postgresql.ENUM(
                "plain_cash",
                "internal_transfer",
                "fx_conversion",
                name="transaction_kind",
                create_type=False,
            ),
            server_default=sa.text("'plain_cash'"),
            nullable=False,
        ),
        sa.Column(
            "direction",
            postgresql.ENUM("buy", "sell", name="transaction_direction", create_type=False),
            nullable=False,
        ),
        sa.Column("base_account_id", sa.BigInteger(), nullable=True),
        sa.Column("quote_account_id", sa.BigInteger(), nullable=True),
        sa.Column("base_currency_code", sa.String(length=8), nullable=False),
        sa.Column("quote_currency_code", sa.String(length=8), nullable=False),
        sa.Column("amount_quote", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("rate", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("amount_base", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column(
            "fee",
            sa.Numeric(precision=20, scale=8),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("fee_currency_code", sa.Text(), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("source", sa.Text(), nullable=True),
        sa.Column("category_id", sa.BigInteger(), nullable=True),
        sa.Column("linked_transaction_id", sa.BigInteger(), nullable=True),
        sa.Column("archived", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["base_account_id"],
            ["accounts.id"],
            name=op.f("fk_fx_transactions_base_account_id_accounts"),
        ),
        sa.ForeignKeyConstraint(
            ["book_id"], ["books.id"], name=op.f("fk_fx_transactions_book_id_books")
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
            name=op.f("fk_fx_transactions_category_id_categories"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_fx_transactions_created_by_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["linked_transaction_id"],
            ["fx_transactions.id"],
            name=op.f("fk_fx_transactions_linked_transaction_id_fx_transactions"),
        ),
        sa.ForeignKeyConstraint(
            ["quote_account_id"],
            ["accounts.id"],
            name=op.f("fk_fx_transactions_quote_account_id_accounts"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fx_transactions")),
    )
    op.create_index(
        "ix_fx_transactions_book_occurred",
        "fx_transactions",
        ["book_id", sa.literal_column("occurred_at DESC")],
        unique=False,
    )
    op.create_index(
        "ix_fx_transactions_book_quote_direction_occurred",
        "fx_transactions",
        ["book_id", "quote_currency_code", "direction", sa.literal_column("occurred_at DESC")],
        unique=False,
    )
    op.create_index(
        "ix_fx_transactions_linked",
        "fx_transactions",
        ["linked_transaction_id"],
        unique=False,
        postgresql_where=sa.text("linked_transaction_id IS NOT NULL"),
    )


def downgrade() -> None:
    op.drop_index(
        "ix_fx_transactions_linked",
        table_name="fx_transactions",
        postgresql_where=sa.text("linked_transaction_id IS NOT NULL"),
    )
    op.drop_index("ix_fx_transactions_book_quote_direction_occurred", table_name="fx_transactions")
    op.drop_index("ix_fx_transactions_book_occurred", table_name="fx_transactions")
    op.drop_table("fx_transactions")
    op.drop_table("tg_chats")
    op.drop_index(
        "ix_notifications_outbox_undelivered",
        table_name="notifications_outbox",
        postgresql_where=sa.text("delivered_at IS NULL"),
    )
    op.drop_table("notifications_outbox")
    op.drop_table("currencies")
    op.drop_index(
        "ix_categories_book_id_parents_tree",
        table_name="categories",
        postgresql_using="gist",
    )
    op.drop_table("categories")
    op.drop_table("book_members")
    op.drop_table("book_invites")
    op.drop_table("accounts")
    op.drop_table("books")
    op.drop_table("users")
    op.drop_index("ix_exchange_rates_base_quote_fetched", table_name="exchange_rates")
    op.drop_table("exchange_rates")
    op.execute("DROP TYPE transaction_direction")
    op.execute("DROP TYPE transaction_kind")
