/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readyz */
        get: operations["readyz_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/telegram": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Auth Telegram */
        post: operations["auth_telegram_api_v1_auth_telegram_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Me */
        get: operations["get_me_api_v1_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/books": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Books */
        get: operations["list_books_api_v1_books_get"];
        put?: never;
        /** Create Book */
        post: operations["create_book_api_v1_books_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/books/{book_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Book */
        get: operations["get_book_api_v1_books__book_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Book */
        patch: operations["patch_book_api_v1_books__book_id__patch"];
        trace?: never;
    };
    "/api/v1/books/{book_id}/switch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Switch Book */
        post: operations["switch_book_api_v1_books__book_id__switch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/books/{book_id}/invites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Invites */
        get: operations["list_invites_api_v1_books__book_id__invites_get"];
        put?: never;
        /** Create Invite */
        post: operations["create_invite_api_v1_books__book_id__invites_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/books/{book_id}/invites/{invite_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke Invite */
        delete: operations["revoke_invite_api_v1_books__book_id__invites__invite_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invites/{token}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept Invite */
        post: operations["accept_invite_api_v1_invites__token__accept_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/books/{book_id}/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Accounts */
        get: operations["list_accounts_api_v1_books__book_id__accounts_get"];
        put?: never;
        /** Create Account */
        post: operations["create_account_api_v1_books__book_id__accounts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts/{account_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Account */
        delete: operations["delete_account_api_v1_accounts__account_id__delete"];
        options?: never;
        head?: never;
        /** Patch Account */
        patch: operations["patch_account_api_v1_accounts__account_id__patch"];
        trace?: never;
    };
    "/api/v1/currencies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Currencies */
        get: operations["list_currencies_api_v1_currencies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/books/{book_id}/currencies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Currency */
        post: operations["add_currency_api_v1_books__book_id__currencies_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/books/{book_id}/fx/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fx Latest */
        get: operations["fx_latest_api_v1_books__book_id__fx_latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/books/{book_id}/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Transactions */
        get: operations["list_transactions_api_v1_books__book_id__transactions_get"];
        put?: never;
        /** Create Transaction */
        post: operations["create_transaction_api_v1_books__book_id__transactions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/books/{book_id}/transactions/export.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Transactions Csv */
        get: operations["export_transactions_csv_api_v1_books__book_id__transactions_export_csv_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/transactions/{tx_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Transaction */
        delete: operations["delete_transaction_api_v1_transactions__tx_id__delete"];
        options?: never;
        head?: never;
        /** Patch Transaction */
        patch: operations["patch_transaction_api_v1_transactions__tx_id__patch"];
        trace?: never;
    };
    "/api/v1/books/{book_id}/reports/weighted-avg-rate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Weighted Avg Rate */
        get: operations["weighted_avg_rate_api_v1_books__book_id__reports_weighted_avg_rate_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/books/{book_id}/reports/account-balance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Account Balance */
        get: operations["account_balance_api_v1_books__book_id__reports_account_balance_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/books/{book_id}/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Categories */
        get: operations["list_categories_api_v1_books__book_id__categories_get"];
        put?: never;
        /** Create Category */
        post: operations["create_category_api_v1_books__book_id__categories_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/categories/{category_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Category */
        delete: operations["delete_category_api_v1_categories__category_id__delete"];
        options?: never;
        head?: never;
        /** Patch Category */
        patch: operations["patch_category_api_v1_categories__category_id__patch"];
        trace?: never;
    };
    "/api/v1/categories/{category_id}/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Move Category */
        post: operations["move_category_api_v1_categories__category_id__move_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/books/{book_id}/transfers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Transfer */
        post: operations["create_transfer_api_v1_books__book_id__transfers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/books/{book_id}/fx-conversions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Fx Conversion */
        post: operations["create_fx_conversion_api_v1_books__book_id__fx_conversions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AccountBalanceSeriesOut */
        AccountBalanceSeriesOut: {
            /** Account Id */
            account_id: number;
            /** Currency Code */
            currency_code: string;
            /** Opening Balance */
            opening_balance: string;
            /** Points */
            points: components["schemas"]["BalancePointOut"][];
        };
        /** AccountCreateIn */
        AccountCreateIn: {
            /** Currency Code */
            currency_code: string;
            /** Name */
            name: string;
            /** Kind */
            kind: number;
            /**
             * Opening Balance
             * @default 0
             */
            opening_balance: string;
        };
        /** AccountOut */
        AccountOut: {
            /** Id */
            id: number;
            /** Book Id */
            book_id: number;
            /** Currency Code */
            currency_code: string;
            /** Name */
            name: string;
            /** Kind */
            kind: number;
            /** Archived */
            archived: boolean;
            /** Opening Balance */
            opening_balance: string;
        };
        /** AccountPatchIn */
        AccountPatchIn: {
            /** Name */
            name?: string | null;
            /** Archived */
            archived?: boolean | null;
        };
        /** AuthTelegramIn */
        AuthTelegramIn: {
            /** Init Data */
            init_data: string;
        };
        /** BalancePointOut */
        BalancePointOut: {
            /**
             * At
             * Format: date-time
             */
            at: string;
            /** Balance */
            balance: string;
        };
        /** BookCreateIn */
        BookCreateIn: {
            /** Name */
            name: string;
            /**
             * Kind
             * @default 0
             */
            kind: number;
            /** Base Currency Code */
            base_currency_code: string;
            /**
             * Default Language
             * @default en
             */
            default_language: string;
        };
        /** BookOut */
        BookOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Kind */
            kind: number;
            /** Base Currency Code */
            base_currency_code: string;
            /** Role */
            role: number;
        };
        /** BookPatchIn */
        BookPatchIn: {
            /** Name */
            name?: string | null;
            /** Archived */
            archived?: boolean | null;
        };
        /** CategoryCreateIn */
        CategoryCreateIn: {
            /** Name */
            name: string;
            /**
             * Kind
             * @default 1
             */
            kind: number;
            /** Parent Id */
            parent_id?: number | null;
            /** Description */
            description?: string | null;
        };
        /** CategoryMoveIn */
        CategoryMoveIn: {
            /** Parent Id */
            parent_id?: number | null;
        };
        /** CategoryOut */
        CategoryOut: {
            /** Id */
            id: number;
            /** Book Id */
            book_id: number;
            /** Parents Tree */
            parents_tree: string;
            /** Depth */
            depth: number;
            /** Kind */
            kind: number;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            /** Archived */
            archived: boolean;
        };
        /** CategoryPatchIn */
        CategoryPatchIn: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            /** Archived */
            archived?: boolean | null;
        };
        /** CurrencyCreateIn */
        CurrencyCreateIn: {
            /** Code */
            code: string;
            /** Symbol */
            symbol: string;
            /** Decimals */
            decimals: number;
            /**
             * Kind
             * @default 0
             */
            kind: number;
        };
        /** CurrencyOut */
        CurrencyOut: {
            /** Id */
            id: number;
            /** Book Id */
            book_id: number | null;
            /** Code */
            code: string;
            /** Symbol */
            symbol: string;
            /** Decimals */
            decimals: number;
            /** Kind */
            kind: number;
            /** Archived */
            archived: boolean;
        };
        /** ErrorDetail */
        ErrorDetail: {
            /** Code */
            code: string;
            /** Params */
            params?: {
                [key: string]: unknown;
            };
        };
        /** ErrorOut */
        ErrorOut: {
            error: components["schemas"]["ErrorDetail"];
            /** Request Id */
            request_id: string;
        };
        /** FxConversionCreateIn */
        FxConversionCreateIn: {
            /** From Account Id */
            from_account_id: number;
            /** To Account Id */
            to_account_id: number;
            /** Amount */
            amount: string;
            /** Rate */
            rate: string;
            /** Occurred At */
            occurred_at?: string | null;
            /** Note */
            note?: string | null;
            /** Category Id */
            category_id?: number | null;
            /** Idempotency Key */
            idempotency_key?: string | null;
        };
        /** FxRateOut */
        FxRateOut: {
            /** Base */
            base: string;
            /** Quote */
            quote: string;
            /** Rate */
            rate: string | null;
            /**
             * Source
             * @default frankfurter
             */
            source: string;
        };
        /** InviteCreateIn */
        InviteCreateIn: {
            /** Role */
            role: number;
            /**
             * Ttl Minutes
             * @default 1440
             */
            ttl_minutes: number;
        };
        /** InviteOut */
        InviteOut: {
            /** Id */
            id: number;
            /** Book Id */
            book_id: number;
            /** Role */
            role: number;
            /** Token */
            token: string;
            /** Deep Link */
            deep_link: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Used At */
            used_at?: string | null;
        };
        /** MeOut */
        MeOut: {
            user: components["schemas"]["UserOut"];
            active_book: components["schemas"]["BookOut"];
            /** Role */
            role: number;
            /** Books */
            books: components["schemas"]["BookOut"][];
        };
        /** TokenOut */
        TokenOut: {
            /** Access Token */
            access_token: string;
            /** Expires In */
            expires_in: number;
            user: components["schemas"]["UserOut"];
            book: components["schemas"]["BookOut"];
        };
        /** TransactionCreateIn */
        TransactionCreateIn: {
            /**
             * Direction
             * @enum {string}
             */
            direction: "buy" | "sell";
            /** Base Currency Code */
            base_currency_code: string;
            /** Quote Currency Code */
            quote_currency_code: string;
            /** Amount Quote */
            amount_quote: string;
            /** Rate */
            rate: string;
            /** Base Account Id */
            base_account_id?: number | null;
            /** Quote Account Id */
            quote_account_id?: number | null;
            /**
             * Fee
             * @default 0
             */
            fee: string;
            /** Fee Currency Code */
            fee_currency_code?: string | null;
            /** Occurred At */
            occurred_at?: string | null;
            /** Note */
            note?: string | null;
            /** Category Id */
            category_id?: number | null;
            /** Idempotency Key */
            idempotency_key?: string | null;
        };
        /** TransactionOut */
        TransactionOut: {
            /** Id */
            id: number;
            /** Book Id */
            book_id: number;
            /** Created By User Id */
            created_by_user_id: number;
            /** Kind */
            kind: string;
            /** Direction */
            direction: string;
            /** Base Currency Code */
            base_currency_code: string;
            /** Quote Currency Code */
            quote_currency_code: string;
            /** Amount Quote */
            amount_quote: string;
            /** Rate */
            rate: string;
            /** Amount Base */
            amount_base: string;
            /** Fee */
            fee: string;
            /** Fee Currency Code */
            fee_currency_code: string | null;
            /** Base Account Id */
            base_account_id: number | null;
            /** Quote Account Id */
            quote_account_id: number | null;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Note */
            note: string | null;
            /** Category Id */
            category_id: number | null;
            /** Archived */
            archived: boolean;
        };
        /** TransactionPage */
        TransactionPage: {
            /** Items */
            items: components["schemas"]["TransactionOut"][];
            /** Next Cursor */
            next_cursor: string | null;
            /** Has More */
            has_more: boolean;
        };
        /** TransactionPatchIn */
        TransactionPatchIn: {
            /** Amount Quote */
            amount_quote?: string | null;
            /** Rate */
            rate?: string | null;
            /** Note */
            note?: string | null;
            /** Occurred At */
            occurred_at?: string | null;
            /** Archived */
            archived?: boolean | null;
        };
        /** TransferCreateIn */
        TransferCreateIn: {
            /** From Account Id */
            from_account_id: number;
            /** To Account Id */
            to_account_id: number;
            /** Amount */
            amount: string;
            /** Occurred At */
            occurred_at?: string | null;
            /** Note */
            note?: string | null;
            /** Category Id */
            category_id?: number | null;
            /** Idempotency Key */
            idempotency_key?: string | null;
        };
        /** UserOut */
        UserOut: {
            /** Id */
            id: number;
            /** Telegram User Id */
            telegram_user_id: number;
            /** First Name */
            first_name?: string | null;
            /** Last Name */
            last_name?: string | null;
            /** Username */
            username?: string | null;
            /** Language */
            language: string;
            /** Timezone */
            timezone: string;
        };
        /** WeightedAvgReportOut */
        WeightedAvgReportOut: {
            /** Book Id */
            book_id: number;
            /** Quote Currency Code */
            quote_currency_code: string;
            /** Direction */
            direction: string;
            /** Weighted Avg Rate */
            weighted_avg_rate: string | null;
            /** Sample Count */
            sample_count: number;
            /** Sum Amount Quote */
            sum_amount_quote: string;
            /** Period From */
            period_from: string | null;
            /** Period To */
            period_to: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    readyz_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    auth_telegram_api_v1_auth_telegram_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthTelegramIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    get_me_api_v1_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    list_books_api_v1_books_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    create_book_api_v1_books_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookCreateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    get_book_api_v1_books__book_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    patch_book_api_v1_books__book_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookPatchIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    switch_book_api_v1_books__book_id__switch_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    list_invites_api_v1_books__book_id__invites_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InviteOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    create_invite_api_v1_books__book_id__invites_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InviteCreateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InviteOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    revoke_invite_api_v1_books__book_id__invites__invite_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: number;
                invite_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: number;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    accept_invite_api_v1_invites__token__accept_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    list_accounts_api_v1_books__book_id__accounts_get: {
        parameters: {
            query?: {
                archived?: boolean | null;
            };
            header?: never;
            path: {
                book_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    create_account_api_v1_books__book_id__accounts_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountCreateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    delete_account_api_v1_accounts__account_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: number;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    patch_account_api_v1_accounts__account_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountPatchIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    list_currencies_api_v1_currencies_get: {
        parameters: {
            query: {
                book_id: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrencyOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    add_currency_api_v1_books__book_id__currencies_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CurrencyCreateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrencyOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    fx_latest_api_v1_books__book_id__fx_latest_get: {
        parameters: {
            query: {
                base: string;
                quote: string;
            };
            header?: never;
            path: {
                book_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FxRateOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    list_transactions_api_v1_books__book_id__transactions_get: {
        parameters: {
            query?: {
                direction?: ("buy" | "sell") | null;
                quote?: string | null;
                account_id?: number | null;
                date_from?: string | null;
                date_to?: string | null;
                archived?: boolean;
                cursor?: string | null;
                page_size?: number;
            };
            header?: never;
            path: {
                book_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    create_transaction_api_v1_books__book_id__transactions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransactionCreateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    export_transactions_csv_api_v1_books__book_id__transactions_export_csv_get: {
        parameters: {
            query?: {
                date_from?: string | null;
                date_to?: string | null;
            };
            header?: never;
            path: {
                book_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    delete_transaction_api_v1_transactions__tx_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tx_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: number;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    patch_transaction_api_v1_transactions__tx_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tx_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransactionPatchIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    weighted_avg_rate_api_v1_books__book_id__reports_weighted_avg_rate_get: {
        parameters: {
            query: {
                quote: string;
                direction: "buy" | "sell";
                date_from?: string | null;
                date_to?: string | null;
            };
            header?: never;
            path: {
                book_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeightedAvgReportOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    account_balance_api_v1_books__book_id__reports_account_balance_get: {
        parameters: {
            query: {
                account_id: number;
                date_from?: string | null;
                date_to?: string | null;
            };
            header?: never;
            path: {
                book_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountBalanceSeriesOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    list_categories_api_v1_books__book_id__categories_get: {
        parameters: {
            query?: {
                include_archived?: boolean;
            };
            header?: never;
            path: {
                book_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    create_category_api_v1_books__book_id__categories_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryCreateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    delete_category_api_v1_categories__category_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                category_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: number;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    patch_category_api_v1_categories__category_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                category_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryPatchIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    move_category_api_v1_categories__category_id__move_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                category_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryMoveIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    create_transfer_api_v1_books__book_id__transfers_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransferCreateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    create_fx_conversion_api_v1_books__book_id__fx_conversions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FxConversionCreateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
}
