// Auto-generated by openapi-typescript from apps/api's OpenAPI 3.1 schema.
// DO NOT EDIT BY HAND. Regenerate via `pnpm types:gen`.
//
// Empty placeholder until M1 generates the first version.

export type paths = Record<string, never>;
export type components = Record<string, never>;
